#!/usr/bin/env bash

#
# baseline
#
# All systems we work with should have some sane basline packages and updates

# Update Ubuntu
sudo apt-get -y update

# Install the build essentials
sudo apt-get -y install build-essential alien
