#!/usr/bin/env bash

#
# install_mysql_client
#
# This script installs only the MySQL client, not a MySQL database server;
# in cases where you need the MySQL client to execute commands on a remote
# MySQL server, such as with Ruby's mysql2 or Python's sqlAlchemy, this is
# what you want


# Create a temporary directory at /tmp/install_mysql_client
mkdir /tmp/install_mysql_client
cd /tmp/install_mysql_client

# Install the MySQL client and dev files
sudo debconf-set-selections <<EOF 
3
EOF
sudo apt-get -y install mysql-client libmysqlclient-dev

# Delete the temporary directory, since we're done with it
rm -rf /tmp/install_mysql_client
