#!/usr/bin/env bash

#
# install_postgres_client
#
# This script installs only the PostgreSQL 9.5 client, not a PostgreSQL database server;
# in cases where you need the PostgreSQL client to execute commands on a remote
# PostgreSQL server, such as with Ruby's pg or Python's sqlAlchemy or psycopg, this is
# what you want

# Install the Postgres 9.5 client
cat << EOF | sudo tee /etc/apt/sources.list.d/postgresql.list
deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5
EOF

wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install postgresql-server-dev-9.5 postgresql-client-9.5


# N.B. the PostgreSQL binaries are located at /usr/pgsql-9.5/bin

